const Routes = {
  LOGIN_STACK: 'LOGIN_STACK',
  LOGIN_SCREEN: 'LOGIN_SCREEN',

  REGISTER_STACK: 'REGISTER_STACK', // REGISTER FLOW
  IMAGE_PROFILE_SCREEN: 'IMAGE_PROFILE_SCREEN',

  HOME_STACK: 'HOME_STACK', // HOMESTACK CONTAINER FOR TABS
  HOME_TABS: 'HOME_TABS', //HOME TABS

};

export default Routes;
