const Routes = {
	LAUNCH_SCREEN: 'LAUNCH_SCREEN',

	LOGIN_STACK: 'LOGIN_STACK',
	LOGIN_SCREEN: 'LOGIN_SCREEN',

	REGISTER_STACK: 'REGISTER_STACK', // REGISTER FLOW
	IMAGE_PROFILE_SCREEN: 'IMAGE_PROFILE_SCREEN',
	PROFILE_SCREEN: 'PROFILE_SCREEN',
	GENDER_SCREEN: 'GENDER_SCREEN',

	HOME_STACK: 'HOME_STACK', // HOMESTACK CONTAINER FOR TABS
	HOME_TABS: 'HOME_TABS', //HOME TABS
	HOME_SCREEN: 'HOME_SCREEN',

	TEACH_STACK: 'TEACH_STACK', // TEACH CONTAINER FOR TABS
	TEACH_TABS: 'TEACH_TABS', //TEACH TABS

	LESSON_STACK: 'LESSON_STACK',
	CREATE_LESSON: 'CREATE_LESSON'
};

export default Routes;
